site_name: Airbnb Project - Documentation
repo_url: https://github.com/codehub-learn/pfizer-dsmasterclass-2022-team1
site_url: https://imanousar.github.io/test/
site_description: An app for predicting Airbnb prices in Athens.
site_author: Giannis Manousaridis, Jenny Cobanaj
use_directory_urls: false

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search

nav:
  - Home: index.md
  - Install: Install/install.md
  - Guides:
      - EDA: Dataset/eda.md
      - Preprocessing: Preprocessing/preprocessing.md
      - Machine Learning: Machine Learning/ml.md
      - REST API: REST API/flask.md
      - Web App: Web App/react.md
      - Deployment: Deployment/deploy.md
  - Acks: Acknowledgements/ack.md
